e_Restaurant/Controllers/ArticleController.cs
using e_Restaurant.Common;
using e_Restaurant.Models;
using e_Restaurant.Repositories;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;

namespace e_Restaurant.Controllers
{
    public class ArticleController : Controller
    {
        private ArticleRepository articleRepo = new ArticleRepository();
        private LanguageRepository langRepo = new LanguageRepository();

        [Authorize(Roles = "Admin, User")]
        public ActionResult Index()
        {
            var article = articleRepo.GetList().Where(a => a.UserID == COM.UserData.ID).OrderByDescending(a => a.data_created);
            return View(article);
        }

        public ActionResult Popular(int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            var article = new PopularPage()
            {
                Popular = articleRepo.ArticlePopular().ToPagedList(pageNumber, pageSize),
                New = articleRepo.ArticleNew().Take(5)
            };

            return View(article);
        }

        public ActionResult New(int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            var article = new NewrPage()
             {
                 Popular = articleRepo.ArticlePopular().Take(5),
                 New = articleRepo.ArticleNew().ToPagedList(pageNumber, pageSize)
             };
            return View(article);
        }

        [Authorize(Roles = "Admin, User")]
        public ActionResult Activate(int id, string articlename)
        {
            var articleModel = new ArticleActivate()
            {
                Article = articleRepo.FindById(id),
                Activate = false
            };
            return View(articleModel);

        }

        [HttpPost]
        public ActionResult Activate(ArticleActivate article, int id)
        {
            articleRepo.Activate(id);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin, User")]
        public ActionResult Deactivate(int id, string articlename)
        {
            var articleModel = new ArticleActivate()
            {
                Article = articleRepo.FindById(id),
                Activate = false
            };
            return View(articleModel);

        }

        [HttpPost]
        public ActionResult Deactivate(ArticleActivate article, int id)
        {
            articleRepo.Deactivate(id);
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id = 0, string articlename = "")
        {
            var articleDetails = new DetailsModel()
            {
                ArticleDetails = articleRepo.Details(id)
            };
            if (articleDetails.ArticleDetails != null)
            {
                if (articlename != StringHelpers.ToSeoUrl(articleDetails.ArticleDetails.title))
                    return RedirectToActionPermanent("Details", new { id = id, articlename = StringHelpers.ToSeoUrl(articleDetails.ArticleDetails.title) });
                else
                {
                    articleRepo.UpdateCountArticle(id);
                    articleDetails.ArticleListPopular = articleRepo.ArticlePopular();
                    return View(articleDetails);
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult EditArtTranslate(int id, int langId)
        {
            var articleTranslate = articleRepo.GetOneArticleTranslate(id, langId);
            return View(articleTranslate);
        }

        [HttpPost]
        public ActionResult EditArtTranslate(ArticleEditTranslate article)
        {
            if (ModelState.IsValid)
            {
                articleRepo.Update(article);
            }
            else
            {
                return View(article);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Translate(int id, string articlename)
        {
            var articleTranslate = new ArticleTranslateModel()
            {
                Article = articleRepo.Details(id),
                Languages = langRepo.GetList()
            };
            return View(articleTranslate);
        }

        [HttpPost]
        public ActionResult Translate(ArticleTranslateModel article, int id)
        {
            articleRepo.AddTranslate(article, id);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin, User, Restaurant")]
        public ActionResult Edit(int id = 0, string articlename = "")
        {
            if (id != 0)
                return View(articleRepo.FindById(id));
            else
                return View(new ArticleModel() { Languages = langRepo.GetListForEdit() });
        }

        // Publish
        [HttpParamAction]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Publish(HttpPostedFileBase[] logo, ArticleModel article)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int? ID = (int?)null;
                    foreach (var file in logo)
                    {
                        if (article.ID != 0)
                        {
                            ID = article.ID;
                            articleRepo.Update(article, file);
                            articleRepo.Activate((int)ID);
                        }
                        else
                        {
                            ID = articleRepo.Create(article, file);
                            articleRepo.Activate((int)ID);
                        }
                        return RedirectToAction("Details", new { id = ID });
                    }
                }
                else
                {
                    if (article.Languages == null || article.Languages.Count() == 0)
                        article.Languages = langRepo.GetListForEdit();
                    return View(article);
                }
            }
            catch (Exception)
            {
                throw;
            }
            return View(article);
        }

        // SaveDraft
        [HttpParamAction]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult SaveDraft(HttpPostedFileBase[] logo, ArticleModel article)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int? ID = (int?)null;
                    foreach (var file in logo)
                    {
                        if (article.ID != 0)
                        {
                            ID = article.ID;
                            articleRepo.Update(article, file);
                            articleRepo.Deactivate((int)ID);
                        }
                        else
                        {
                            ID = articleRepo.Create(article, file);
                            articleRepo.Deactivate((int)ID);
                        }
                        return RedirectToAction("Details", new { id = ID });
                    }
                }
                else
                {
                    if (article.Languages == null || article.Languages.Count() == 0)
                        article.Languages = langRepo.GetListForEdit();
                    return View(article);
                }
            }
            catch (Exception)
            {
                throw;
            }
            return View(article);
        }

        [Authorize(Roles = "Admin, User,Restaurant")]
        public ActionResult Delete(int id, string articlename)
        {
            var article = articleRepo.Details(id);
            return View(article);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, string articlename)
        {
            articleRepo.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            articleRepo.Dispose();
            base.Dispose(disposing);
        }
    }
}

e_Restaurant/Controllers/RestaurantController.cs
using e_Restaurant.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using e_Restaurant.Repositories;
using e_Restaurant.Common;
using PagedList.Mvc;
using PagedList;

namespace e_Restaurant.Controllers
{
    public class RestaurantController : Controller
    {
        private readonly RestaurantRepository restaurantRepo = new RestaurantRepository();
        private readonly UnitRepository unitRepo = new UnitRepository();
        private readonly ArticleRepository articleRepo = new ArticleRepository();
        private readonly RatingRepsitory ratingRepo = new RatingRepsitory();

        [HttpGet]
        public ActionResult Index(string name)
        {
            var restaurant = restaurantRepo.RestaurantDetails(name);
            if (restaurant != null)                            
                return View(restaurant);            
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Index(RestaurantDetailsModel restaurant)
        {
            if (ModelState.IsValid && User.Identity.IsAuthenticated)
            {
                ratingRepo.Vote(restaurant);
            }
            return RedirectToAction("Index", new { name = restaurant.Reference });
        }

        [HttpGet]
        public ActionResult GetUnitList(int id)
        {
            return Json(
                ViewToString.RenderViewToString(this, "~/Views/Restaurant/_Menu.cshtml", unitRepo.GetUnitListByID(id))
                , JsonRequestBehavior.AllowGet);
        }

        public ActionResult City(string city, int? page)
        {
            if (string.IsNullOrEmpty(city))
                return RedirectToAction("Index", "Home");
            else
            {
                int pageSize = 6;
                int pageNumber = (page ?? 1);
                var searchCityModel = new RestaurantSearchCityModel();
                searchCityModel.Result = restaurantRepo.GetListByCity(city).ToPagedList(pageNumber, pageSize);
                searchCityModel.ArticlePopular = articleRepo.ArticlePopular();

                return View(searchCityModel);
            }
        }
    }
}

e_Restaurant/Controllers/SearchController.cs
using e_Restaurant.Models;
using e_Restaurant.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;

namespace e_Restaurant.Controllers
{
    public class SearchController : Controller
    {
        private readonly SearchRepository searchRepo = new SearchRepository();
        private readonly RestaurantRepository restaurantRepo = new RestaurantRepository();
        private readonly ArticleRepository articleRepo = new ArticleRepository();

        [HttpGet]
        public ActionResult Index(string q)
        {
            return PartialView(searchRepo.Search(q));
        }

        public ActionResult Cities(string searchstring, int? page)
        {
            int pageSize = 6;
            int pageNumber = (page ?? 1);

            var searchCityModel = new RestaurantSearchCityModel();
            searchCityModel.Result = searchRepo.RestaurantByCities(searchstring).ToPagedList(pageNumber, pageSize);
            searchCityModel.ArticlePopular = articleRepo.ArticlePopular();
            return View(searchCityModel);
        }

        public ActionResult Restaurants(string searchstring, int? page)
        {
            if (string.IsNullOrEmpty(searchstring))
                return RedirectToAction("Index", "Home");
            else
            {
                int pageSize = 6;
                int pageNumber = (page ?? 1);
                var searchRestaurant = new RestaurantSearchCityModel();
                searchRestaurant.Result = searchRepo.RestaurantName(searchstring).ToPagedList(pageNumber, pageSize);
                searchRestaurant.ArticlePopular = articleRepo.ArticlePopular();
                return View(searchRestaurant);
            }
        }

        public ActionResult Articles(string searchstring)
        {            
            var searchArticleModel = new ArticleSearchModel();
            searchArticleModel.Result = searchRepo.Articles(searchstring);
            searchArticleModel.ArticlePopular = articleRepo.ArticlePopular();
            return View(searchArticleModel);
        }
    }
}

e_Restaurant/Views/Search/Articles.cshtml
@model e_Restaurant.Models.ArticleSearchModel
@using e_Restaurant.Common

@{
    ViewBag.Title = "Articles";
}

@Html.Partial("_SearchForm")

<style>
    div#main {
        padding: 0 !important;
    }
</style>

<div id="wrapper_category_page_trial" class="wrapper_category_trial">
    <div class="category_name" id="highratedCategory">
        @if (Model.Result.Any())
        {
            <strong>@COM.GetTranslation("LBL_WEFOUND_RESULTS")</strong>
        }
        else
        {
            <strong>@COM.GetTranslation("LBL_NO_RESULTS")</strong>
        }
    </div>
    <div id="articles_category_popular">
        <span style="margin-left: 7px"><b>@COM.GetTranslation("LABEL_RIGHT_MENU_TOP_ONE_LVL")</b> </span>
    </div>

    <div id="restaurantList">
        @if (Model != null && Model.Result.Any())
        {                            @Html.Partial("~/Views/Article/partial/_List.cshtml", Model.Result)        
            
        }
    </div>
    <div class="col-md-3">
        @Html.Partial("~/Views/Article/partial/_Top.cshtml", Model.ArticlePopular)
    </div>
    <div style="clear: both"></div>
</div>

e_Restaurant/Views/Search/Cities.cshtml
@model e_Restaurant.Models.RestaurantSearchCityModel
@using e_Restaurant.Common
@using PagedList.Mvc;
@{
    ViewBag.Title = "E-RestaurantNFC: search " + @ViewContext.RouteData.Values["city"];
}

@Html.Partial("_SearchForm")

<style>
    div#main {
        padding: 0 !important;
    }
</style>

<div id="wrapper_category_page_trial" class="wrapper_category_trial">
   
    <div class="category_name" id="highratedCategory">
        <strong>@COM.GetTranslation("LBL_WEFOUND_RESULTS")</strong>
    </div>
    <div id="articles_category_popular">
        <span style="margin-left: 7px"><b>@COM.GetTranslation("LABEL_RIGHT_MENU_TOP_ONE_LVL")</b> </span>
    </div>

    <div style="float: left">
        @if (Model != null && Model.Result.Any())
        {
            foreach (var modelItem in Model.Result)
            {
            @Html.Partial("~/Views/Home/_RestaurantList.cshtml", modelItem)        
            }
            @Html.PagedListPager(Model.Result, page => Url.Action("Cities", new { page }),
                new PagedListRenderOptions
                {
                    LinkToPreviousPageFormat = String.Format(COM.GetTranslation("LABEL_PREV_BTN")),
                    LinkToNextPageFormat = String.Format(COM.GetTranslation("LABEL_NEXT_BTN")),
                    MaximumPageNumbersToDisplay = 6
                })
        }
        else
        {
            <span>Restaurants in this city are absent</span>
        }
    </div>
    <div class="col-md-3">
        @Html.Partial("~/Views/Article/partial/_Top.cshtml", Model.ArticlePopular)
    </div>
    <div style="clear: both"></div>

</div>

e_Restaurant/Views/Search/Index.cshtml
@model e_Restaurant.Models.SearchModel
@using e_Restaurant.Common

<div class="category_name" id="highratedCategory">
    @if (Model.TotalCities > 0 || Model.TotalRestaurants > 0 || Model.TotalArticles > 0)
    {
        <b>@COM.GetTranslation("LBL_WEFOUND_RESULTS")</b>
    }
    else
    {
        <b>@COM.GetTranslation("LBL_NO_RESULTS")</b>
    }
</div>
<div id="articles_category_popular">
    <span style="margin-left: 7px"><b>@COM.GetTranslation("LABEL_RIGHT_MENU_TOP_ONE_LVL")</b> </span>
</div>

<div id="restaurantList">
    @if (Model.Cities.Any())
    {     
        <div class="searchheader">
            <span>@COM.GetTranslation("COMMON_CITY")</span>
            <img src="@Url.Content("~/Images/Search_City.png")" />
            <div class="linkallresults">
                @if (Model.TotalCities > 3)
                {@Html.ActionLink(string.Format(COM.GetTranslation("LBL_SHOW_ALL"), Model.TotalCities), "Cities", "Search", new { searchstring = Model.SearchText }, null)}
            </div>
        </div> 
        <table class="searchCities">
            @foreach (var item in Model.Cities)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.Country + " " + item.City, "City", "Restaurant", new { city = item.City }, null)
                    </td>
                </tr>
            }
        </table>
    }


    @if (Model.Restaurants.Any())
    {
        <div class="searchheader">
            <span>@COM.GetTranslation("LABEL_LEFT_MENU_TOP")</span>
            <img src="@Url.Content("~/Images/Search_Restaurant.png")" />
            <div class="linkallresults">
                @if (Model.TotalRestaurants > 3)
                {@Html.ActionLink(string.Format(COM.GetTranslation("LBL_SHOW_ALL"), Model.TotalRestaurants), "Restaurants", "Search", new { searchstring = Model.SearchText }, null)}
            </div>
        </div>
                foreach (var item in Model.Restaurants)
                {
        @Html.Partial("~/Views/Home/_RestaurantList.cshtml", item)
                }
    }
    @if (Model.Articles.Any())
    {
        <div class="searchheader">
            <span>@COM.GetTranslation("HEADER_SEARCH_ARTICLES")</span>
            <img src="@Url.Content("~/Images/Search_Articles.png")" />
            <div class="linkallresults">
                @if (Model.TotalArticles > 3)
                {@Html.ActionLink(string.Format(COM.GetTranslation("LBL_SHOW_ALL"), Model.TotalArticles), "Articles", "Search", new { searchstring = Model.SearchText }, null)}
            </div>
        </div>
        
        @Html.Partial("~/Views/Article/partial/_List.cshtml", Model.Articles)
    }
</div>

<div class="col-md-3">
    @Html.Partial("~/Views/Article/partial/_Top.cshtml", Model.ArticlesPopular)
</div>
<div style="clear: both"></div>

e_Restaurant/Views/Search/Restaurants.cshtml
@model e_Restaurant.Models.RestaurantSearchCityModel
@using PagedList.Mvc;
@using e_Restaurant.Common

@Html.Partial("_SearchForm")

<style>
    div#main {
        padding: 0 !important;
    }
</style>

<div id="wrapper_category_page_trial" class="wrapper_category_trial">
    <div class="category_name" id="highratedCategory">
        @if (Model.Result.Any())
        {
            <strong>@COM.GetTranslation("LBL_WEFOUND_RESULTS")</strong>
        }
        else
        {
            <strong>@COM.GetTranslation("LBL_NO_RESULTS")</strong>
        }
    </div>
    <div id="articles_category_popular">
        <span style="margin-left: 7px"><b>@COM.GetTranslation("LABEL_RIGHT_MENU_TOP_ONE_LVL")</b> </span>
    </div>
    
    <div id="restaurantList">
        @if (Model != null && Model.Result.Any())
        {
            foreach (var modelItem in Model.Result)
            {
                @Html.Partial("~/Views/Home/_RestaurantList.cshtml", modelItem)        
            }
            @Html.PagedListPager(Model.Result, page => Url.Action("Restaurants", new { page }),
                new PagedListRenderOptions
                {
                    LinkToPreviousPageFormat = String.Format("< {0}", COM.GetTranslation("LABEL_PREV_BTN")),
                    LinkToNextPageFormat = String.Format("{0} >", COM.GetTranslation("LABEL_NEXT_BTN")),
                    MaximumPageNumbersToDisplay = 6
                })
        }
    </div>
    <div class="col-md-3">
        @Html.Partial("~/Views/Article/partial/_Top.cshtml", Model.ArticlePopular)
    </div>
    <div style="clear: both"></div>
</div>