e_Restaurant/Controllers/ArticleController.cs
using e_Restaurant.Common;
using e_Restaurant.Models;
using e_Restaurant.Repositories;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;

namespace e_Restaurant.Controllers
{
    public class ArticleController : Controller
    {
        private ArticleRepository articleRepo = new ArticleRepository();
        private LanguageRepository langRepo = new LanguageRepository();

        [Authorize(Roles = "Admin, User")]
        public ActionResult Index()
        {
            var article = articleRepo.GetList().Where(a => a.UserID == COM.UserData.ID).OrderByDescending(a => a.data_created);
            return View(article);
        }

        public ActionResult Popular(int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            var article = new PopularPage()
            {
                Popular = articleRepo.ArticlePopular().ToPagedList(pageNumber, pageSize),
                New = articleRepo.ArticleNew().Take(5)
            };

            return View(article);
        }

        public ActionResult New(int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            var article = new NewrPage()
             {
                 Popular = articleRepo.ArticlePopular().Take(5),
                 New = articleRepo.ArticleNew().ToPagedList(pageNumber, pageSize)
             };
            return View(article);
        }

        [Authorize(Roles = "Admin, User")]
        public ActionResult Activate(int id, string articlename)
        {
            var articleModel = new ArticleActivate()
            {
                Article = articleRepo.FindById(id),
                Activate = false
            };
            return View(articleModel);

        }

        [HttpPost]
        public ActionResult Activate(ArticleActivate article, int id)
        {
            articleRepo.Activate(id);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin, User")]
        public ActionResult Deactivate(int id, string articlename)
        {
            var articleModel = new ArticleActivate()
            {
                Article = articleRepo.FindById(id),
                Activate = false
            };
            return View(articleModel);

        }

        [HttpPost]
        public ActionResult Deactivate(ArticleActivate article, int id)
        {
            articleRepo.Deactivate(id);
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id = 0, string articlename = "")
        {
            var articleDetails = new DetailsModel()
            {
                ArticleDetails = articleRepo.Details(id)
            };
            if (articleDetails.ArticleDetails != null)
            {
                if (articlename != StringHelpers.ToSeoUrl(articleDetails.ArticleDetails.title))
                    return RedirectToActionPermanent("Details", new { id = id, articlename = StringHelpers.ToSeoUrl(articleDetails.ArticleDetails.title) });
                else
                {
                    articleRepo.UpdateCountArticle(id);
                    articleDetails.ArticleListPopular = articleRepo.ArticlePopular();
                    return View(articleDetails);
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult EditArtTranslate(int id, int langId)
        {
            var articleTranslate = articleRepo.GetOneArticleTranslate(id, langId);
            return View(articleTranslate);
        }

        [HttpPost]
        public ActionResult EditArtTranslate(ArticleEditTranslate article)
        {
            if (ModelState.IsValid)
            {
                articleRepo.Update(article);
            }
            else
            {
                return View(article);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Translate(int id, string articlename)
        {
            var articleTranslate = new ArticleTranslateModel()
            {
                Article = articleRepo.Details(id),
                Languages = langRepo.GetList()
            };
            return View(articleTranslate);
        }

        [HttpPost]
        public ActionResult Translate(ArticleTranslateModel article, int id)
        {
            articleRepo.AddTranslate(article, id);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin, User, Restaurant")]
        public ActionResult Edit(int id = 0, string articlename = "")
        {
            if (id != 0)
                return View(articleRepo.FindById(id));
            else
                return View(new ArticleModel() { Languages = langRepo.GetListForEdit() });
        }

        // Publish
        [HttpParamAction]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Publish(HttpPostedFileBase[] logo, ArticleModel article)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int? ID = (int?)null;
                    foreach (var file in logo)
                    {
                        if (article.ID != 0)
                        {
                            ID = article.ID;
                            articleRepo.Update(article, file);
                            articleRepo.Activate((int)ID);
                        }
                        else
                        {
                            ID = articleRepo.Create(article, file);
                            articleRepo.Activate((int)ID);
                        }
                        return RedirectToAction("Details", new { id = ID });
                    }
                }
                else
                {
                    if (article.Languages == null || article.Languages.Count() == 0)
                        article.Languages = langRepo.GetListForEdit();
                    return View(article);
                }
            }
            catch (Exception)
            {
                throw;
            }
            return View(article);
        }

        // SaveDraft
        [HttpParamAction]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult SaveDraft(HttpPostedFileBase[] logo, ArticleModel article)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int? ID = (int?)null;
                    foreach (var file in logo)
                    {
                        if (article.ID != 0)
                        {
                            ID = article.ID;
                            articleRepo.Update(article, file);
                            articleRepo.Deactivate((int)ID);
                        }
                        else
                        {
                            ID = articleRepo.Create(article, file);
                            articleRepo.Deactivate((int)ID);
                        }
                        return RedirectToAction("Details", new { id = ID });
                    }
                }
                else
                {
                    if (article.Languages == null || article.Languages.Count() == 0)
                        article.Languages = langRepo.GetListForEdit();
                    return View(article);
                }
            }
            catch (Exception)
            {
                throw;
            }
            return View(article);
        }

        [Authorize(Roles = "Admin, User,Restaurant")]
        public ActionResult Delete(int id, string articlename)
        {
            var article = articleRepo.Details(id);
            return View(article);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, string articlename)
        {
            articleRepo.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            articleRepo.Dispose();
            base.Dispose(disposing);
        }
    }
}

e_Restaurant/Views/Article/Activate.cshtml
@model e_Restaurant.Models.ArticleActivate
@using e_Restaurant.Common
@{
    ViewBag.Title = @COM.GetTranslation("LABEL_ACTIVATE");
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@if (Model.Article != null)
{ 
    <div style="margin-left: 15px;">
        @using (Html.BeginForm("Activate", "Article"))
        { @Html.ValidationSummary(true)
            @Html.ValidationSummary(true)
            <p style="text-align: center; padding-right: 140px;">
                <input type="submit" value="@COM.GetTranslation("LABEL_ACTIVATE")" class="button" style="width: 220px;" />
            </p>
        }
    </div>
    <div id="newArticles">
        <div id="Article">
            @if (!string.IsNullOrEmpty(Model.Article.Logo))
            {
                <img id="articlesImage" src="@Url.Action("Index", "Thumbnail", new { ImagePath = Url.Content("~" + string.Format(ImageLink.Article.LogoDirectory, Model.Article.ID, Model.Article.Logo)), width = 300, height = 200 })" width="300" height="200" align='left';/>
            }
            else
            { <img id="articlesImage" src="@Url.Content("~/Images/Nofoto.png")" width="300" height="200" align='left';/>}
            <div id="articleTitle"><strong>@Html.DisplayFor(model => model.Article.Title)</strong></div>
            <div id="articleDescription">
                <i>@Html.Raw(Model.Article.ShortText)</i>
            </div>
            <div id="articleText">
                @Html.Raw(Model.Article.FullText)
            </div>
            <br>
            <span>@COM.GetTranslation("LABEL_ARTICLE_TAGS"):</span> <a href="#">@Model.Article.Tag</a>
        </div>
    </div>

   
    <div style="margin-left: 30px;">
        <p>@Html.ActionLink(@COM.GetTranslation("LABEL_BACK_TO_MY_ARTICLE"), "Index")</p>
    </div>
}
else
{
    <p>
        @COM.GetTranslation("LABEL_ARTICLE_NOT_FOUND")
    </p>
}

e_Restaurant/Views/Article/Deactivate.cshtml
@model e_Restaurant.Models.ArticleActivate
@using e_Restaurant.Common
@{
    ViewBag.Title = "Deactivate";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@if (Model.Article != null)
{ 
    <div style="margin-left: 15px;">
        @using (Html.BeginForm("Deactivate", "Article"))
        { @Html.ValidationSummary(true)
            @Html.ValidationSummary(true)
            <p style="text-align: center; padding-right: 140px;">
                <input type="submit" value="@COM.GetTranslation("BTN_SEND_IN_A_DRAFT")" class="button" style="width: 220px;" />
            </p>
        }
    </div>
    <div id="newArticles">
        <div id="Article">
            @if (!string.IsNullOrEmpty(Model.Article.Logo))
            {
                <img id="articlesImage" src="@Url.Action("Index", "Thumbnail", new { ImagePath = Url.Content("~" + string.Format(ImageLink.Article.LogoDirectory, Model.Article.ID, Model.Article.Logo)), width = 300, height = 200 })" width="300" height="200" align='left';/>
            }
            else
            { <img id="articlesImage" src="@Url.Content("~/Images/Nofoto.png")" width="300" height="200" align='left';/>}
            <div id="articleTitle"><strong>@Html.DisplayFor(model => model.Article.Title)</strong></div>
            <div id="articleDescription">
                <i>@Html.Raw(Model.Article.ShortText)</i>
            </div>
            <div id="articleText">
                @Html.Raw(Model.Article.FullText)
            </div>
            <br>
            <span>@COM.GetTranslation("LABEL_ARTICLE_TAGS"):</span> <a href="#">@Model.Article.Tag</a>
        </div>
    </div>
    <div style="margin-left: 30px;">
        <p>@Html.ActionLink(@COM.GetTranslation("LABEL_BACK_TO_MY_ARTICLE"), "Index")</p>
    </div>
}
else
{
    <p>
        @COM.GetTranslation("LABEL_ARTICLE_NOT_FOUND")
    </p>
}

e_Restaurant/Views/Article/Delete.cshtml
@model e_Restaurant.Models.ArticleDetailsModel
@using e_Restaurant.Common
@{
    ViewBag.Title = @COM.GetTranslation("TITLE_DELETE_ARTICLE");
}

<div style="margin-left: 40px;">

    @using (Html.BeginForm())
    {
        <span style="font-size: 24px;">@COM.GetTranslation("LABEL_DELETE_MESSAGE_ARTICLE")?</span>
        <input type="submit" value="@COM.GetTranslation("LABEL_ARTICLE_DELETE_BTN")" class="button" />
        <span>|</span>@*
        @Html.ActionLink(@COM.GetTranslation("LABEL_CANCEL"), "Details", "Article", new { articlename = Model.ID })*@
        <a href="javascript:window.history.back()">@COM.GetTranslation("LABEL_CANCEL")</a>      
    }
</div>
<table>
    <tbody>
        <tr>
            <td valign="top">
                <div id="newArticles">
                    <div id="Article">
                        <img id="articlesImage" src="@Url.Action("Index", "Thumbnail", new { ImagePath = Url.Content(Model.logo), width = 300, height = 200 })" width="300" height="200" align='left';/>
                        <div id="articleTitle" class="title-font-size"><strong>@Html.DisplayFor(model => model.title)</strong></div>
                        <div id="articleDate">@COM.GetTranslation("LABEL_ARTICLE_POSTED") @String.Format("{0:D}", Model.data_created) by @Html.DisplayFor(model => model.UserName)</div>
                        <div id="articleDescription">
                            <i>@Html.Raw(Model.short_text)</i>
                        </div>
                        <div id="articleText">
                            @Html.Raw(@Model.full_text)
                        </div>
                        <br>
                        @if (!string.IsNullOrEmpty(Model.tag))
                        { 
                            <span>@COM.GetTranslation("LABEL_ARTICLE_TAGS"): </span><a href="#">@Model.tag</a>
                        }
                    </div>

                </div>
            </td>
            <td></td>
</table>

e_Restaurant/Views/Article/Details.cshtml
@model e_Restaurant.Models.DetailsModel
@using e_Restaurant.Common
@{
    ViewBag.Title = Model.ArticleDetails.title + " | E-RestaurantNFC";
}
@section head{
    <meta name="description" content="@Model.ArticleDetails.short_text" />
    @if (!string.IsNullOrEmpty(@Model.ArticleDetails.tag))
    {<meta name="Keywords" content="@Model.ArticleDetails.tag" />}
}
<table>
    <tbody>
        <tr>
            <td valign="top">
                @Html.Partial("~/Views/Article/partial/_Details.cshtml", Model.ArticleDetails)
            </td>
            <td valign="top">
                <div id="popularArticles">
                    <div id="articles_category_popular">
                        <span style="margin-left: 7px"><b>@COM.GetTranslation("LABEL_RIGHT_MENU_TOP_ONE_LVL")</b> </span>
                    </div>
                    @Html.Partial("~/Views/Article/partial/_Top.cshtml", Model.ArticleListPopular.Take(4))
                </div>
            </td>
        </tr>
    </tbody>
</table>

e_Restaurant/Views/Article/Edit.cshtml
@model e_Restaurant.Models.ArticleModel
@using e_Restaurant.Common
@{

    ViewBag.Title = Model.ID > 0 ? @COM.GetTranslation("LABEL_EDIT_ARTICLE") + " " + Model.Title : @COM.GetTranslation("LABEL_ARTICLE_ADD_NEW");
}
<style type="text/css">
    .editor-field input[type="text"] {
        width: 100%;
    }
</style>

<script type="text/javascript">
    $(document).ready(function () {
        // input logo readURL

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#previewFile').attr('src', '@Url.Content("~/Images/Nofoto.png")');
                    $('#previewFile').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
                }
            }
        $("#logo").change(function () {
            $('#previewFile').attr('src', '@Url.Content("~/Images/Nofoto.png")');
            readURL(this);
        });
        // end input logo readURL

        //popup Article Prewiev
        $(function () {
            $("#dialog").dialog({
                autoOpen: false,
                width: 820,
                modal: true,
                title: '@COM.GetTranslation("LABEL_ARTICLE_PREVIEW")',
                buttons: {
                    Ok: function () {
                        $(this).dialog("close");
                    }
                },
                show: {
                    effect: "blind",
                    duration: 1000
                },
                hide: {
                    effect: "fade",
                    duration: 1000
                }
            });
            $("#opener").click(function () {
                $("#dialog").dialog("open");
                input = $('#logo').val();
                $('#previewFile').prop('src')
                if (input == '') {
                    $('#articlesImage').prop('src', $('#previewFile').prop('src').toString());
                }
                $('#articlesImage').prop('src', $('#previewFile').prop('src'));
                $('#articleTitle').text($('#Title').val());
                $('#articleDescription').html($('#ShortText').val());
                $('#articleText').html($('#FullText').val());
                $('a#Tag').text($('#Tag').val());
            });
        });
    });
</script>
@if ((Model.ID > 0 && Model.UserID == COM.UserData.ID) ||
     (Model.ID > 0 && COM.UserData.Role[0] == "Admin") ||
     Model.ID == 0)
{<div style="margin: 20px;">
    @using (Html.BeginForm("Edit", "Article", FormMethod.Post, new { enctype = "multipart/form-data", @id = "EditForm" }))
    {
        @Html.ValidationSummary(true)
        
        <div class="editor-label">
            @Html.LabelFor(model => model.LanCode)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.LanCode, Model.Languages, "----------")
            @Html.ValidationMessageFor(model => model.LanCode)
        </div>

        <br />
        <div class="editor-label">
            @Html.LabelFor(model => model.Logo)
        </div>
        <div style="width: 200px;">
            @if (!string.IsNullOrEmpty(Model.Logo))
            { 
                <img  id="previewFile" src="@Url.Content("~" + string.Format(ImageLink.Article.LogoDirectory, Model.ID, Model.Logo))" width="200" height="150" alt=""/>
            }
            else
            {
                <img id="previewFile" src="" width="200" height="150" alt="Image preview..." />
            }
        </div>

        <div class="editor-field">
            <input type="file" name="logo" id="logo" accept="image/*" />
            @Html.ValidationMessageFor(model => model.Logo)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field ">
            @Html.TextBoxFor(model => model.Title, new { autocomplete = "off", @maxlength = "55" })<br />
            @Html.ValidationMessageFor(model => model.Title)
        </div>
        <span id="count"></span>
        <div class="editor-label">
            @Html.LabelFor(model => model.ShortText)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.ShortText, new { autocomplete = "off", rows = "3", @style = "width:100%", maxlength = "300" })
            @Html.ValidationMessageFor(model => model.ShortText)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FullText)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FullText)
            @Html.ValidationMessageFor(model => model.FullText)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Tag)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tag)<br />
            @Html.ValidationMessageFor(model => model.Tag)
        </div>
        @Html.HiddenFor(model => model.ID)
        <br />      
        <div class="row" style="margin: 0px;">
            <div class="col-md-4">
                <input id="opener" type="button" value="@COM.GetTranslation("LABEL_ARTICLE_PREVIEW")" class="button"/>
            </div>
            <div class="col-md-4">
                <p style="text-align: center;">
                    <input type="submit" value="@COM.GetTranslation(Model.ID > 0 ? "LABEL_UPDATE_BTN" : "LABEL_BTN_ADD_ARTICLE")" class="button" name="publish" style="width:200px;"/>
                </p>
            </div>
            <div class="col-md-4">
                <p style="text-align: right;">
                    <input type="submit" value="@COM.GetTranslation("BTN_SAVE_IN_DRAFT")" name="saveDraft" class="button" />
                </p>
            </div>
        </div>
        
        <div>
            <p style="text-align: right;">@Html.ActionLink(@COM.GetTranslation("LABEL_BACK_TO_MY_ARTICLE"), "Index")</p>
        </div>                 
    }
    </div>
}
else
{
    <div style="margin: 10px">
        <strong style="font-size: 20px;">@COM.GetTranslation("LABEL_ACCESS_DENIED")</strong>
    </div>
}

<div id="dialog" title="@COM.GetTranslation("LABEL_ARTICLE_PREVIEW")">
    <div id="newArticles">
        <div id="Article">
            <img id="articlesImage" src="" width="300" height="200" align='left' />
            <div id="articleTitle"><strong>Title</strong></div>
            <div id="articleDate">@COM.GetTranslation("LABEL_ARTICLE_POSTED") @System.DateTime.Now.ToString() </div>
            <div id="articleDescription">
                <i>ShortText</i>
            </div>
            <div id="articleText">
                FullText
            </div>
            <br>
            <span>@COM.GetTranslation("LABEL_ARTICLE_TAGS"):</span><a id="Tag" href="#">Tag</a>
        </div>
    </div>
</div>

<script src="@Url.Content("~/Scripts/jquery-ui-1.11.2.js")"></script>

e_Restaurant/Views/Article/EditArtTranslate.cshtml
@model e_Restaurant.Models.ArticleEditTranslate
@using e_Restaurant.Common
@{
    ViewBag.Title = @COM.GetTranslation("TITLE_EDIT_TRANSLATION");
}

<style type="text/css">
    .editor-field input[type="text"] {
        width: 95%;
    }
</style>
<div style="margin-left: 15px;">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <fieldset>
            <legend>Edit translation for article </legend>
            @Html.HiddenFor(model => model.ID)
              @Html.HiddenFor(model => model.LanCode)
            <div class="editor-label">
                @Html.LabelFor(model => model.Title)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.ShortText)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ShortText)
                @Html.ValidationMessageFor(model => model.ShortText)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.FullText)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.FullText)
                @Html.ValidationMessageFor(model => model.FullText)
            </div>
            <br />
            <p>
                <input type="submit" value="Save" class="button" />
            </p>
        </fieldset>
    }
</div>
<div>
       @if (HttpContext.Current.User.Identity.IsAuthenticated)
        { 
            @Html.ActionLink(@COM.GetTranslation("LABEL_BACK_TO_MY_ARTICLE"), "Index")
        }
   
</div>

e_Restaurant/Views/Article/Index.cshtml
@model IEnumerable<e_Restaurant.Models.ArticleDetailsModel>
@using e_Restaurant.Common

@{
    ViewBag.Title = @COM.GetTranslation("LABEL_ACTIVE_LIST");
}

<style type="text/css">
    div#main {
        padding: 0 !important;
    }

    .ui-tabs .ui-tabs-nav li {
        width: 49.5%;
        background: rgba(20,40,73,1);
        text-align: center;
    }

        .ui-tabs .ui-tabs-nav li.ui-tabs-active {
            position: relative;
        }

            .ui-tabs .ui-tabs-nav li.ui-tabs-active a {
                width: 100%;
            }

        .ui-tabs .ui-tabs-nav li a:hover {
            /*background: rgba(0,0,0,0.5);*/
            background: #992222;
        }

    .ui-widget-content {
        border: none;
        background: none;
        background: rgba(20,40,73,1);
    }

    .ui-widget-header {
        background: rgba(20,40,73,1);
        border: none;
        background: none;
    }

    .ui-widget {
        font: 15px 'Lora', sans-serif;
    }

    .ui-tabs .ui-tabs-nav .ui-tabs-anchor {
        background: rgba(20,40,73,1);
        color: white;
        width: 100%;
    }

    .workPanel {
        margin-left: -44px;
    }

    .articleContainer {
        margin-left: 155px;
    }
</style>

@Html.Partial("_SearchForm")
<div id="horizontal_category_menu">
    <ul class="category_menu">
        <li>@Html.ActionLink(COM.GetTranslation("LABEL_LEFT_MENU_TOP"), "Index", "Home")
        </li>
        <li><a href="#">@COM.GetTranslation("LABEL_RIGHT_MENU_TOP")</a>
            <ul id="category_menu_articles">
                <li>@Html.ActionLink(@COM.GetTranslation("LABEL_RIGHT_MENU_TOP_ONE_LVL"), "Popular", "Article")</li>
                <li>@Html.ActionLink(@COM.GetTranslation("LABEL_RIGHT_MENU_TOP_TWO_LVL"), "New", "Article")</li>
            </ul>
        </li>
    </ul>
</div>
<div id="wrapper_category_page_trial" class="wrapper_category_trial" style="padding: 0px 0px 10px 0px;">
    <br />
    @if (HttpContext.Current.User.Identity.IsAuthenticated)
    { 
        <p style="margin-left: 15px;">
            @Html.ActionLink(@COM.GetTranslation("LABEL_ARTICLE_ADD_NEW"), "Edit", "Article")
        </p>
    }
    <script src="@Url.Content("~/Scripts/jquery-ui-1.11.2.min.js")"></script>
    <script>
        $(function () {
            $("#tabs").tabs();
        });
    </script>
    <div id="tabs" style="background-color: rgb(233, 234, 236); box-shadow: 0 0 5px rgba(0,0,0,0.5); width: 99%;">
        <ul>
            <li><a href="#tabs-1">@COM.GetTranslation("TAB_LABEL_PUBLISHED")</a></li>
            <li><a href="#tabs-2">@COM.GetTranslation("TAB_LABEL_UNPUBLISHED")</a></li>
        </ul>
        <div id="tabs-1">
            @Html.Partial("~/Views/Article/partial/_List.cshtml", Model.Where(a => a.Active == true))
            <div style="clear: both;"></div>
        </div>
        <div id="tabs-2">
            @Html.Partial("~/Views/Article/partial/_List.cshtml", Model.Where(a => a.Active == false))
            <div style="clear: both"></div>
        </div>

    </div>
</div>